Repository fluid-project/trivet, pull requests merged in 2023-08, with the labels that each got.

#343 feat: disallow GPT from crawling any Trivet-based sites
  src/robots.njk
Labels: enhancement

#351 fix: resolve sitemap parsing error in Chrome
  src/sitemap.njk
Labels: bug

#353 fix: resolve issues with localized pagination
  .github/pull_request_template.md
  src/_includes/layouts/posts.njk
  src/_includes/partials/components/pagination.njk
  src/_locales/fr-CA/messages.mo
  src/_locales/fr-CA/messages.po
  src/_locales/messages.js
  src/collections/pages/en-CA/posts.md
  src/collections/pages/fr-CA/posts.md
Labels: bug

#352 chore(docs): update README with information about Trivet Monolingual
  README.md
Labels: documentation

#354 fix: move generatePermalink out of eleventyComputed
  src/collections/pages/en-CA/posts.md
  src/collections/pages/fr-CA/posts.md
  src/collections/pages/pages.11tydata.js
  src/collections/posts/en-CA/post-1.md
  src/collections/posts/en-CA/post-10.md
  src/collections/posts/en-CA/post-11.md
  src/collections/posts/en-CA/post-2.md
  src/collections/posts/en-CA/post-3.md
  src/collections/posts/en-CA/post-4.md
  src/collections/posts/en-CA/post-5.md
  src/collections/posts/en-CA/post-6.md
  src/collections/posts/en-CA/post-7.md
  src/collections/posts/en-CA/post-8.md
  src/collections/posts/en-CA/post-9.md
  src/collections/posts/fr-CA/post-1.md
  src/collections/posts/fr-CA/post-10.md
  src/collections/posts/fr-CA/post-11.md
  src/collections/posts/fr-CA/post-2.md
  src/collections/posts/fr-CA/post-3.md
  src/collections/posts/fr-CA/post-4.md
  src/collections/posts/fr-CA/post-5.md
  src/collections/posts/fr-CA/post-6.md
  src/collections/posts/fr-CA/post-7.md
  src/collections/posts/fr-CA/post-8.md
  src/collections/posts/fr-CA/post-9.md
  src/collections/posts/posts.11tydata.js
Labels: enhancement

#355 fix: better YAML pattern to handle .github files as well as config.yml
  .github/dependabot.yml
  .github/workflows/docker.yml
  .github/workflows/lint-build.yml
  .github/workflows/release-please.yml
  package.json
Labels: bug, enhancement

#356 chore(deps): bump eleventy-plugin-fluid to 2.3.2
  package-lock.json
  package.json
Labels: dependencies, javascript

#357 chore(deps-dev): prevent updates to Stylelint >= 15
  .github/dependabot.yml
Labels: dependencies

#362 fix: simplify YAML lint config
  .eslintrc.js
  package.json
Labels: enhancement

#369 fix: use more descriptive script names for linting (S)CSS and JavaScript
  package.json
Labels: enhancement

#371 feat: replace Netlify CMS with Decap CMS
  eleventy.config.js
  package-lock.json
  package.json
  src/admin/admin.njk
  src/admin/config.yml
Labels: enhancement, dependencies
